/* tslint:disable */
/* eslint-disable */
/**
 * kartografia-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AppDTO,
} from '../models';
import {
    AppDTOFromJSON,
    AppDTOToJSON,
} from '../models';

export interface ApiAppsIdDeleteRequest {
    id: number;
}

export interface ApiAppsNamePostRequest {
    name: string;
}

export interface ApiAppsPutRequest {
    appDTO?: AppDTO;
}

/**
 * 
 */
export class AppsApi extends runtime.BaseAPI {

    /**
     * Get all application
     */
    async apiAppsGetRaw(token: string,initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<AppDTO>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/Apps`,
            method: 'GET',
            headers: {
                ...headerParameters,
                'Authorization': `Bearer ${token}`,
              },
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AppDTOFromJSON));
    }

    /**
     * Get all application
     */
    async apiAppsGet(token: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<AppDTO>> {
        const response = await this.apiAppsGetRaw(token,initOverrides);
        return await response.value();
    }

    /**
     * Delete app by id
     */
    async apiAppsIdDeleteRaw(token: string, requestParameters: ApiAppsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling apiAppsIdDelete.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/Apps/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'DELETE',
            headers: {
                ...headerParameters,
                'Authorization': `Bearer ${token}`,
              },
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete app by id
     */
    async apiAppsIdDelete(token: string,requestParameters: ApiAppsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiAppsIdDeleteRaw(token, requestParameters, initOverrides);
    }

    /**
     * Add new app
     */
    async apiAppsNamePostRaw(token: string,requestParameters: ApiAppsNamePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters.name === null || requestParameters.name === undefined) {
            throw new runtime.RequiredError('name','Required parameter requestParameters.name was null or undefined when calling apiAppsNamePost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/Apps/{name}`.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters.name))),
            method: 'POST',
            headers: {
                ...headerParameters,
                'Authorization': `Bearer ${token}`,
              },
            query: queryParameters,
        }, initOverrides);

        return new runtime.TextApiResponse(response) as any;
    }

    /**
     * Add new app
     */
    async apiAppsNamePost(token: string,requestParameters: ApiAppsNamePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.apiAppsNamePostRaw(token,requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update existing app
     */
    async apiAppsPutRaw(token: string,requestParameters: ApiAppsPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/Apps`,
            method: 'PUT',
            headers: {
                ...headerParameters,
                'Authorization': `Bearer ${token}`,
              },
            query: queryParameters,
            body: AppDTOToJSON(requestParameters.appDTO),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Update existing app
     */
    async apiAppsPut(token: string, requestParameters: ApiAppsPutRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiAppsPutRaw(token,requestParameters, initOverrides);
    }

}
