/* tslint:disable */
/* eslint-disable */
/**
 * kartografia-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AuditDTO,
} from '../models';
import {
    AuditDTOFromJSON,
    AuditDTOToJSON,
} from '../models';

/**
 * 
 */
export class AuditApi extends runtime.BaseAPI {

    /**
     */
    async apiAuditGetRaw(token: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<AuditDTO>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/Audit`,
            method: 'GET',
            headers: {
                ...headerParameters,
                'Authorization': `Bearer ${token}`,
              },
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AuditDTOFromJSON));
    }

    /**
     */
    async apiAuditGet(token: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<AuditDTO>> {
        const response = await this.apiAuditGetRaw(token, initOverrides);
        return await response.value();
    }

}
